//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Solution.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Solution.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To unapprove you need to first approve the record.
        /// </summary>
        public static string ApprovalRequired {
            get {
                return ResourceManager.GetString("ApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved successfully.
        /// </summary>
        public static string ApprovedSuccessfully {
            get {
                return ResourceManager.GetString("ApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code emailed successfully.
        /// </summary>
        public static string CodeEmailedSuccessfully {
            get {
                return ResourceManager.GetString("CodeEmailedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code does not match.
        /// </summary>
        public static string CodeUnmatched {
            get {
                return ResourceManager.GetString("CodeUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert in database.
        /// </summary>
        public static string DatabaseInsertFailed {
            get {
                return ResourceManager.GetString("DatabaseInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate data.
        /// </summary>
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is inactive, cannot be updated.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial approval required.
        /// </summary>
        public static string InitialApprovalRequired {
            get {
                return ResourceManager.GetString("InitialApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserted successfully.
        /// </summary>
        public static string InsertedSuccessfully {
            get {
                return ResourceManager.GetString("InsertedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are invalid.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid details.
        /// </summary>
        public static string InvalidDetails {
            get {
                return ResourceManager.GetString("InvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent masters are inactive or not found.
        /// </summary>
        public static string MasterIsInActive {
            get {
                return ResourceManager.GetString("MasterIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more voyages have been already approved.
        /// </summary>
        public static string MultiPassagesApproved {
            get {
                return ResourceManager.GetString("MultiPassagesApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passage is already approved, unable to update.
        /// </summary>
        public static string PassageAlreadyApproved {
            get {
                return ResourceManager.GetString("PassageAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully.
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in use.
        /// </summary>
        public static string RecordInUse {
            get {
                return ResourceManager.GetString("RecordInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token was not found.
        /// </summary>
        public static string RefreshTokenMissing {
            get {
                return ResourceManager.GetString("RefreshTokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token was revoked.
        /// </summary>
        public static string RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report created successfully.
        /// </summary>
        public static string ReportCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ReportCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error.
        /// </summary>
        public static string TechnicalError {
            get {
                return ResourceManager.GetString("TechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel is mapped in group, unable to make it inactive.
        /// </summary>
        public static string UnableVesselDelete {
            get {
                return ResourceManager.GetString("UnableVesselDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved successfully.
        /// </summary>
        public static string UnapprovedSuccessfully {
            get {
                return ResourceManager.GetString("UnapprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure not found.
        /// </summary>
        public static string UnitOfMeasureNotFound {
            get {
                return ResourceManager.GetString("UnitOfMeasureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure threshold already exists.
        /// </summary>
        public static string UnitOfMeasureThresholdExist {
            get {
                return ResourceManager.GetString("UnitOfMeasureThresholdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure threshold not found.
        /// </summary>
        public static string UnitOfMeasureThresholdNotFound {
            get {
                return ResourceManager.GetString("UnitOfMeasureThresholdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure threshold updated successfully.
        /// </summary>
        public static string UnitOfMeasureThresholdUpdated {
            get {
                return ResourceManager.GetString("UnitOfMeasureThresholdUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure type not found.
        /// </summary>
        public static string UnitOfMeasureTypeNotFound {
            get {
                return ResourceManager.GetString("UnitOfMeasureTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is available.
        /// </summary>
        public static string UsernameAvailable {
            get {
                return ResourceManager.GetString("UsernameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not available.
        /// </summary>
        public static string UsernameNotAvailable {
            get {
                return ResourceManager.GetString("UsernameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid token.
        /// </summary>
        public static string ValidToken {
            get {
                return ResourceManager.GetString("ValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Verification Code is {0}.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
    }
}
