//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Solution.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VeslinkApisResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VeslinkApisResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Solution.Resources.VeslinkApisResource", typeof(VeslinkApisResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/agent/portcalls?apiToken={0}&amp;arrivalFromDays={1}&amp;arrivalToDays=v1/agent/portcalls?apiToken={0}&amp;arrivalFromDays={1}&amp;arrivalToDays={2}.
        /// </summary>
        public static string GetAllAgents {
            get {
                return ResourceManager.GetString("GetAllAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/companies/partners?apiToken={0}.
        /// </summary>
        public static string GetAllCompanies {
            get {
                return ResourceManager.GetString("GetAllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/delayTypes/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllDelaytype {
            get {
                return ResourceManager.GetString("GetAllDelaytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/fuelTypes/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllFueltype {
            get {
                return ResourceManager.GetString("GetAllFueltype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/ports/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllPortCalls {
            get {
                return ResourceManager.GetString("GetAllPortCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/ports/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllPorts {
            get {
                return ResourceManager.GetString("GetAllPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/suppliers/{0}/bunkering?apiToken={1}.
        /// </summary>
        public static string GetAllSuppliers {
            get {
                return ResourceManager.GetString("GetAllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/vessels/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllVessel {
            get {
                return ResourceManager.GetString("GetAllVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/vessels/{0}?apiToken={1}.
        /// </summary>
        public static string GetAllVessels {
            get {
                return ResourceManager.GetString("GetAllVessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/cargoes/{0}?apiToken={1}.
        /// </summary>
        public static string GetCargoes {
            get {
                return ResourceManager.GetString("GetCargoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/fuelTypes/{0}/{1}?apiToken={2}.
        /// </summary>
        public static string GetComapanyFueltype {
            get {
                return ResourceManager.GetString("GetComapanyFueltype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/delayTypes/{0}/{1}?apiToken={2}.
        /// </summary>
        public static string GetDelaytype {
            get {
                return ResourceManager.GetString("GetDelaytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/forms?apiToken={0}&amp;amp;formIdentifier={1}&amp;amp;startDate={2}&amp;amp;endDate={3}&amp;amp;vesselCode={4}&amp;amp;voyageNo={5}&amp;amp;portNo={6}&amp;amp;formStatus={7}.
        /// </summary>
        public static string GetFormsList {
            get {
                return ResourceManager.GetString("GetFormsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/portActivities/{0}?apiToken={1}.
        /// </summary>
        public static string GetPortActivities {
            get {
                return ResourceManager.GetString("GetPortActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/ports/{0}/{portNo}?apiToken={1}.
        /// </summary>
        public static string GetPortByNo {
            get {
                return ResourceManager.GetString("GetPortByNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/unitsOfMeasure/{0}/{1}?apiToken={2}.
        /// </summary>
        public static string GetUnitMeasure {
            get {
                return ResourceManager.GetString("GetUnitMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/unitsOfMeasure/{0}?apiToken={1}.
        /// </summary>
        public static string GetUnitMeasureList {
            get {
                return ResourceManager.GetString("GetUnitMeasureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/vessels/{0}/{1}?apiToken={2}.
        /// </summary>
        public static string GetVesselbyCode {
            get {
                return ResourceManager.GetString("GetVesselbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/fuelTypes/{0}?apiToken={1}&amp;vesselCode={2}.
        /// </summary>
        public static string GetVesselFueltype {
            get {
                return ResourceManager.GetString("GetVesselFueltype", resourceCulture);
            }
        }
    }
}
