using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Solution.Models
{
    public class FuelType :CommonField   // It is Fuel and Fluid List page of wireframe.
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long FuelTypeId { get; set; }        //Fuel Type Id is autogenerated.
        public long FuelTypeVeslinkId { get; set; }   // Fuel Type Id of veslink
        public string Type { get; set; }            //Fuel Abbreviation of wireframe.
        public string Name { get; set; }
        public bool TrackSulfurContent { get; set; }
        public virtual UnitofMeasure UnitofMeasure { get; set; }
        [ForeignKey("UnitofMeasure")]
        public long? UnitofMeasureId { get; set; }
        public virtual FuelCategory FuelCategory { get; set; }
        [ForeignKey("FuelCategory")]
        public long FuelCategoryId { get; set; }
        public string Description { get; set; }     // most probably this would be alias name of wireframe but not sure.
        public bool IsLowSulfur { get; set; }
        public decimal FuelDensity { get; set; }
        public decimal FuelDensityTemperature { get; set; }
        public decimal CalorificValue { get; set; }
        public string Alias { get; set; }
    }
}
